--------------------------------------------------------
--  DDL for Table B_MATCHES
--------------------------------------------------------

  CREATE TABLE "ROCKETLEAGUE"."B_MATCHES" 
   (	"MTC_CODE" NUMBER(*,0), 
	"MTC_REQ_CODE" NUMBER(*,0), 
	"MTC_RESULT" VARCHAR2(20 BYTE), 
	"MTC_RANK_CHANGE" NUMBER(*,0), 
	"MTC_GOALS" NUMBER(*,0), 
	"MTC_ASSISTS" NUMBER(*,0), 
	"MTC_SAVES" NUMBER(*,0), 
	"MTC_SHOTS" NUMBER(*,0), 
	"MTC_MVP" NUMBER(*,0), 
	"MTC_TIER" NUMBER, 
	"MTC_DIVISION" NUMBER, 
	"MTC_UNIXSTAMP" NUMBER, 
	"MTC_ISOSTAMP" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
