--------------------------------------------------------
--  Constraints for Table B_PLAYLIST_STATS
--------------------------------------------------------

  ALTER TABLE "ROCKETLEAGUE"."B_PLAYLIST_STATS" ADD CONSTRAINT "B_SEASON_STATS_UK1" UNIQUE ("PST_SEASON_NUMBER", "PST_PLAYLIST_ID", "PST_MATCHES_PLAYED")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKETLEAGUE"."B_PLAYLIST_STATS" MODIFY ("PST_DIVISION" NOT NULL ENABLE);
  ALTER TABLE "ROCKETLEAGUE"."B_PLAYLIST_STATS" MODIFY ("PST_TIER" NOT NULL ENABLE);
  ALTER TABLE "ROCKETLEAGUE"."B_PLAYLIST_STATS" MODIFY ("PST_RANK_POINTS" NOT NULL ENABLE);
  ALTER TABLE "ROCKETLEAGUE"."B_PLAYLIST_STATS" MODIFY ("PST_MATCHES_PLAYED" NOT NULL ENABLE);
  ALTER TABLE "ROCKETLEAGUE"."B_PLAYLIST_STATS" MODIFY ("PST_PLAYLIST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ROCKETLEAGUE"."B_PLAYLIST_STATS" MODIFY ("PST_PLAYLIST_ID" NOT NULL ENABLE);
  ALTER TABLE "ROCKETLEAGUE"."B_PLAYLIST_STATS" MODIFY ("PST_SEASON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ROCKETLEAGUE"."B_PLAYLIST_STATS" MODIFY ("PST_REQ_CODE" NOT NULL ENABLE);
  ALTER TABLE "ROCKETLEAGUE"."B_PLAYLIST_STATS" ADD CONSTRAINT "B_SEASON_STATS_PK" PRIMARY KEY ("PST_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKETLEAGUE"."B_PLAYLIST_STATS" MODIFY ("PST_CODE" NOT NULL ENABLE);
