--------------------------------------------------------
--  DDL for Table B_PLAYLIST_STATS
--------------------------------------------------------

  CREATE TABLE "ROCKETLEAGUE"."B_PLAYLIST_STATS" 
   (	"PST_CODE" NUMBER(*,0), 
	"PST_REQ_CODE" NUMBER, 
	"PST_SEASON_NUMBER" NUMBER(*,0), 
	"PST_PLAYLIST_ID" NUMBER, 
	"PST_PLAYLIST_NAME" VARCHAR2(200 BYTE), 
	"PST_MATCHES_PLAYED" NUMBER, 
	"PST_RANK_POINTS" NUMBER, 
	"PST_TIER" NUMBER, 
	"PST_DIVISION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
