--------------------------------------------------------
--  DDL for Table B_REQUESTS
--------------------------------------------------------

  CREATE TABLE "ROCKETLEAGUE"."B_REQUESTS" 
   (	"REQ_CODE" NUMBER, 
	"REQ_UPDATED_AT" NUMBER, 
	"REQ_NEXT_UPDATE_AT" NUMBER, 
	"REQ_TIMESTAMP" NUMBER, 
	"REQ_WINS" NUMBER, 
	"REQ_GOALS" NUMBER, 
	"REQ_MVPS" NUMBER, 
	"REQ_SAVES" NUMBER, 
	"REQ_SHOTS" NUMBER, 
	"REQ_ASSISTS" NUMBER, 
	"REQ_PLAYLIST_TYPE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
